### PR TITLE
Add an activity diagram of the rhythm pairing

### PR DESCRIPTION
**Pull request by jverbraeken**
- Relevant Issues: #109
- Related Pull Requests: -

* * *

## What
This PR adds an activity diagram of the rhythm pairing to the repository

## Why
This is done because the rhythm pairing #109 is pretty complex

## How
I made an activity diagram with GenMyModel

## Alternative implementation
-

## Notes
-

### CODE REVIEW

**Comment by clenrock** [comment]
I'm not really sure about the diagram, it's confusing that you sometimes use 'master' and 'slave' but I also see 'client' being used. 
The note with 'top = master' is not fully visible, the bottom is wrapped.
Last point; why do you have the 'start app' block? I think we can assume the apps are already opened when they are pairing

**Comment by ericcornelissen** [comment]
> I think we can assume the apps are already opened when they are pairing

I think we cannot just assume that, I think that must be true.

* * *

My initial response:
- I think its easier to just send the correct tab pattern to the slave and verify it on the slave machine, instead of sending the pattern of the slave back to the master.
- I think you can leave out the part after sending the public key as this is not specific to this scenario.
- I think its better that when the pattern of the slave is incorrect, the connection is stoppend and the users have to restart the connection. But I'm interested as to why you choose to take this approach.

**Comment by TheBonheurs** [comment]
I also have a few questions. First of all I think pairing should be included by both, otherwise how do you know who the master and who the slave is? Next up, what does wait for the tap on the screen mean? Wait for the tap from the master or something else? After checking the rhythm and finding out it's wrong shouldn't the master re-tap a (new) rhythm?

**Comment by jverbraeken** [comment]
@clenrock @ericcornelissen @TheBonheurs Thanks for your reviews!

**Comment by jverbraeken** [comment]
@clenrock I changed client to slave. The note should be fully visible now, I think that the start app block is, as @ericcornelissen pointed out, needed, but we can discuss about that

**Comment by jverbraeken** [comment]
@ericcornelissen I think it's dangerous to send the correct pattern to the slave, because a MITM can just very, very easy just say that his pattern matches.
I'm not sure if we should leave out the part after sending the public keys, as you can also see under the definition of done of #109. My goal was to have a fully functional public key exchange this or next week, and when you cannot add contacts, the feature is not usable at all.

My idea about tapping the rhythm is that when the user makes a mistake while tapping he can just immediately start over again without having to touch any button. Will speak about that during the meeting

**Comment by jverbraeken** [comment]
@TheBonheurs I'm not sure about your first point, will speak to you about that during the meeting. Wait for a tap on the screen on the top means that the app waits for a tap from the master on the (almost) screen-filling button @clenrock made. About your last point, same as @ericcornelissen , not sure what the best way is. We'll have to discuss that

**Comment by ericcornelissen** [comment]
> I think it's dangerous to send the correct pattern to the slave, because a MITM can just very, very easy just say that his pattern matches.

Fair point 😄 


> I'm not sure if we should leave out the part after sending the public keys, as you can also see under the definition of done of #109. My goal was to have a fully functional public key exchange this or next week, and when you cannot add contacts, the feature is not usable at all.

You don't have to leave it out entirely, but the details are not needed here imo since this diagram is about the rhythm pairing. You're also leaving out opening the app and selecting the pairing method...


> My idea about tapping the rhythm is that when the user makes a mistake while tapping he can just immediately start over again without having to touch any button.

This is possible, but not very intuitive imo so you have to work this out a little better.

**Comment by jverbraeken** [comment]
@ericcornelissen Updated the diagram!

**Comment by clenrock** [comment]
@jverbraeken  It still includes the 'start app' part

**Comment by ericcornelissen** [comment]
A few comments on clearness of the text:
- `Pair over Bluetooth` should be `Select pair over Bluetooth`
- `Tab rhythm` should be `Select tab rhythm`


Also, I think the diagram should be a bit more linear... I created a quick and dirty example for you (not fully thought through ofcourse) 😄 
quick dirty

**Comment by jverbraeken** [comment]
@clenrock Eric disagrees with you:

> I think we cannot just assume that, I think that must be true.

**Comment by ericcornelissen** [comment]
I actually changed my mind on that. We should keep the start app balloon, but there should also be a branch where the app is already opened.

I think that whenever someone wants to connect with you you get a notification for this and clicking on this will start the pairing process.

**Comment by jverbraeken** [comment]
@clenrock @ericcornelissen Implemented your suggestions!

**Comment by ericcornelissen** [comment]
Still have a few remarks 😅 
- I think the slave should already be notified as soon as it is selected from the Bluetooth devices list. So it should be moved a bit to the left and there should be some kind of arrow indicating that it is being notified.
- The exchange of keys at the end of the diagram looks really weird... I understand the diagram and it seems correct, but due to the fact that "Send public key to master" and "New contact" are lined up so perfectly it kinda feels like the master only gets the slaves public key once the key accepted the contact... Maybe spread this out a bit 😄

**Comment by jverbraeken** [comment]
@ericcornelissen Implemented your suggestions!

**Comment by ericcornelissen** [comment]
Nice update! Got two remaining comments:
- Shouldn't the "Waiting for slave" and "Wait for taps from slave" be after one another? Are these really supposed to happen in parallel?
- Did you think about what should happen if at any point in time the connection fails? Most interesting, imo, would be the situation where the master send his details to the slave but then the connection breaks before the slave can respond with their details.
  In that case, do we want the slave to be able to add the master as a contact, I'm not so sure...? In this scenario I would image the master and slave would want to retry the exchange from the start, otherwise the master can't receive the details of the slave. In which case already having the master as contact can be annoying...

**Comment by jverbraeken** [comment]
@ericcornelissen I implemented your first suggestion, but I'm not sure about the second one. The diagram will become very messy when I indicate what should happen in case of a connection failure for all nodes where data is sent over Bluetooth. I think it's best to just show the user an error message when onBluetoothConnectionLost is called and then give the user the option if he wants to retry or to cancel the public key exchange. 

If A received the public key from B, but due to a network failure B didn't receive the public key from A, then A can still add person B imo. Public keys are public, it's no problem if you know the public key of some person while that person doesn't know the public key of you.

**Pull request merged**
