### PR TITLE
Add logo to the app as startup icon, closes #92

### LINKED ISSUE #92: Change the default app logo
- Parent issues: -
- Relevant issues: -
- Estimated effort: -

* * *

## User story
As a user I want to recognize the app by looking at its logo so that I can easier recognize it.

## What
This issue demands to replace the default logo with the Nervous Fish logo

## Why
This issue is needed for the project because we want to make it easy for users to find the application in their application list

## How
This feature can be added by replacing the default logo with the Nervous Fish logo

## Definition of done
This task can be considered done when

- The default logo is replaced by the Nervous Fish logo

### PR DESCRIPTION
**Pull request by clenrock**
- Relevant Issues: #92 
- Related Pull Requests: -

* * *

## What
This adds a logo which can be seen when starting up the app.

## Why
This Pull Request is needed because it makes the app more professional looking.

## How
This feature can be viewed/tested within the project by starting the app, but then going back to the list with apps.

## Notes
It now automatically takes the 'round' logo instead of the normal logo. The round logo has a white circle behind it.

### CODE REVIEW

**Comment by TheBonheurs** [comment]
I agree with @jverbraeken !

**Comment by clenrock** [comment]
@TheBonheurs @jverbraeken Fixed it!

**Comment by clenrock** [comment]
@ericcornelissen I just tried to do all the sizes, so that it looks great on all devices!

**Comment by ericcornelissen** [comment]
@clenrock I understand that but `app/src/main/res/drawable-hdpi/nervous_fish_logo_round.png` (and `app/src/main/res/drawable-hdpi/nervous_fish_logo.png` for that matter) isn't used...

**Comment by clenrock** [comment]
@ericcornelissen Sorry, I didn't understand you at first. Those are not used indeed, I will delete them

**Pull request merged**
