### PR TITLE
Make it possible to click on the label, fixes the bug #216

### PR DESCRIPTION
**Pull request by clenrock**
- Relevant Issues: #216 
- Related Pull Requests: -

* * *

## What
This Pull Request adds to the repository a fix for the bug described at #216.

## How
This feature can be viewed/tested within the project by opening the MainActivity and clicking on the fab button's label.

## Notes
Unfortunately I had to make the switch-case an if-else statement

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Have you considered looking at the `labelFor` property of the `Label` in order to get the ID of the actual button?

**Comment by clenrock** [comment]
@ericcornelissen No, do you think that makes a nicer solution?

**Comment by ericcornelissen** [comment]
If it works it would because you could keep the `switch`-statement

**Comment by clenrock** [comment]
@ericcornelissen I tried it, but the ID that is returned is not the one of the button. So I'll keep it like this

**Comment by ericcornelissen** [comment]
Too bad 😢

**Pull request merged**
